# Generated by Django 2.2.7 on 2019-12-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_fix_default_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.Team')),
            ],
        ),
    ]
