# Generated by Django 2.2.7 on 2019-12-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_fix_default_is_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_add_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=1023)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='profiles.Team')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'collections',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='backlog',
            options={'verbose_name': 'Backlog', 'verbose_name_plural': 'Backlogs'},
        ),
        migrations.AlterField(
            model_name='backlog',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='backlog', serialize=False, to='profiles.Team'),
        ),
        migrations.AlterModelTable(
            name='backlog',
            table='backlogs',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='projects.Collection')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'db_table': 'lists',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=1023)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last change date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Deadline date')),
                ('units', models.PositiveIntegerField(default=0, verbose_name='Number of units')),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to=settings.AUTH_USER_MODEL)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.Backlog')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.List')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
    ]
