# Generated by Django 2.2.7 on 2019-11-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_fix_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-date_started'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-date_created'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='membership',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='Is manager?'),
        ),
    ]
