# Generated by Django 2.2.8 on 2020-01-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='profiles.Team', unique=True),
        ),
    ]
